supergraph:
    path: /graphql
    listen: 0.0.0.0:5220
headers:
    all:
        request:
            - propagate:
                named: Authorization
traffic_shaping:
    all:
        deduplicate_query: true
